apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - image: application:0.2
        name: application
        args:
        - -XX:MaxRAMPercentage=60.0
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - name: http
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        volumeMounts:
          - name: myconfig
            mountPath: /myconfig
      volumes:
        - name: myconfig
          configMap:
            name: myconfig
